### PR TITLE
SOLR-95: Support ISNI (and IPI) for Artist and Label fuzzy search

### PR DESCRIPTION
**Pull request by yvanzo**
# Summary
* This is a…
    * [x] Feature addition
* Support ISNI (and IPI) for Artist and Label fuzzy search

# Problem

* JIRA ticket: [SOLR-95](https://tickets.metabrainz.org/browse/SOLR-95)

(Note: IPI is already supported for Label fuzzy search, and is already indexed for both Artist and Label.)

### CODE REVIEW

**Comment by zas** [comment]
@samj1912 : you didn't reviewed this yet

**Comment by samj1912** [comment]
Is this actually needed? Otherwise we will be spending a lot unnecessary processing power on it. Can we actually get the number of queries using this explicitly?

**Comment by yvanzo** [comment]
Decided not to merge. Rather make MusicBrainz website search field `isni` when input matches ISNI RE.

**Comment by yvanzo** [comment]
Including isni field in fuzzy search has been abandoned, but adding isni field to label schema was necessary for indexation. Now done in pull request https://github.com/metabrainz/mbsssss/pull/53.

**Pull request closed without merging**
